### ISSUE TITLE
Bridge should automatically notify when people join or leave the chatroom

### ISSUE THREAD

**Issue by eblis** [andreimoldo/node-slack-bridge#3]
When a new person enters or leaves the chatroom it would be nice if the bridge automatically sent a message telling who joined/left.

**Comment by eblis** [comment]
Does slack allow some kind of flags for the messages ?

I wonder if the joins messages could be made so that they don't flash the window (do not treat these notification as new messages).

**Comment by andreimoldo** [comment]
There isn't support for something like this.
